shamefullyHoist: true

catalogs:
  default:
    "@antfu/eslint-config": ^5.2.2
    eslint: ^9.34.0
    node-modules-inspector: ^1.1.1
  kazariex:
    "@swapswap/typescript-plugin": ^0.0.2
    kerria: 0.2.4
    maestrale: ^0.1.3
    plain-shiki: ^0.3.0
    pm3genscript: ^0.1.10
    propathy: ^0.2.1
    zaff: ^1.4.0
    zfeed: ^0.2.3
  zinkawaii:
    "@zinkawaii/eslint-config": ^0.4.1
    "@zinkawaii/scripts": ^0.0.3
    "@zinkawaii/stylelint-config": ^0.3.3
    "@zinkawaii/tsconfig": ^0.0.2
    create-zin: ^0.0.12

onlyBuiltDependencies:
  - unrs-resolver
