shamefullyHoist: true

catalog:
  "@antfu/eslint-config": ^4.16.1
  eslint: ^9.30.0
  node-modules-inspector: ^1.0.0

catalogs:
  kazariex:
    kerria: 0.2.4
    maestrale: ^0.1.3
    plain-shiki: ^0.3.0
    pm3genscript: ^0.1.10
    propathy: ^0.2.1
    zaff: ^1.4.0
    zfeed: ^0.2.3
  zinkawaii:
    "@zinkawaii/eslint-config": ^0.3.0
    "@zinkawaii/scripts": ^0.0.2
    "@zinkawaii/stylelint-config": ^0.3.2
    "@zinkawaii/tsconfig": ^0.0.2
    create-zin: ^0.0.11

onlyBuiltDependencies:
  - unrs-resolver
