shamefullyHoist: true

catalog:
  "@antfu/eslint-config": ^4.13.1
  eslint: ^9.26.0
  node-modules-inspector: ^0.6.8

catalogs:
  kazariex:
    kerria: 0.2.4
    maestrale: ^0.1.3
    plain-shiki: ^0.2.0
    pm3genscript: ^0.1.10
    propathy: ^0.2.1
    zaff: ^1.4.0
  zinkawaii:
    "@zinkawaii/eslint-config": ^0.3.0
    "@zinkawaii/scripts": ^0.0.2
    "@zinkawaii/stylelint-config": ^0.3.1
    "@zinkawaii/tsconfig": ^0.0.2
    create-zin: ^0.0.11

onlyBuiltDependencies:
  - unrs-resolver
